# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 10:05
from __future__ import unicode_literals

from moneyed import RUB, Money
from django.db import migrations
from random import randint

from test_admin_panel.models import SimpleMoneyModel


def fill_test_data(a, b):
    for x in range(10):
        SimpleMoneyModel(pay=Money(randint(0, 100), RUB)).save()


class Migration(migrations.Migration):

    dependencies = [
        ('test_admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_test_data)
    ]
